# Generated by Django 3.2.9 on 2021-11-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
